// Mock data for development and testing
import { Product, Booking } from "@/types";

export const mockProducts: Product[] = [
    {
        SimID: 1,
        SimListName: "Formula Pro Racing Simulator",
        PricePerHour: 1500,
        ListDescription:
            "Experience professional-grade Formula racing with our state-of-the-art simulator. Features direct drive wheel, triple 32-inch monitors, and motion platform.",
        HostID: 1,
        ModID: 1,
        ModelName: "Formula Pro",
        Description: "Professional racing simulator with motion platform",
        BrandID: 1,
        BrandName: "SimRacing Pro",
        FName: "John",
        LName: "Smith",
        AddressDetail: "123 Racing Ave, Downtown",
        Lat: 13.7563,
        Long: 100.5018,
        Htel: "02-123-4567",
        firstimage: "formula1.jpg",
        secondimage: "formula2.jpg",
        thirdimage: "formula3.jpg",
    },
    {
        SimID: 2,
        SimListName: "GT Championship Simulator",
        PricePerHour: 1200,
        ListDescription:
            "High-performance GT racing experience with Fanatec DD2 wheel, VR support, and realistic force feedback. Perfect for endurance racing enthusiasts.",
        HostID: 2,
        ModID: 2,
        ModelName: "GT Pro",
        Description: "High-performance GT simulator with VR",
        BrandID: 2,
        BrandName: "GT Racing",
        FName: "Sarah",
        LName: "Johnson",
        AddressDetail: "456 Speed Blvd, Central District",
        Lat: 13.7465,
        Long: 100.5379,
        Htel: "02-234-5678",
        firstimage: "gt1.jpg",
        secondimage: "gt2.jpg",
        thirdimage: "gt3.jpg",
    },
    {
        SimID: 3,
        SimListName: "Rally Master Simulator",
        PricePerHour: 1000,
        ListDescription:
            "Feel every bump and slide with our rally simulator. Hydraulic handbrake, rally-spec wheel, and surround sound system for maximum immersion.",
        HostID: 1,
        ModID: 3,
        ModelName: "Rally Master",
        Description: "Rally simulator with hydraulic handbrake",
        BrandID: 1,
        BrandName: "SimRacing Pro",
        FName: "John",
        LName: "Smith",
        AddressDetail: "789 Track Road, North Side",
        Lat: 13.765,
        Long: 100.538,
        Htel: "02-345-6789",
        firstimage: "rally1.jpg",
        secondimage: "rally2.jpg",
        thirdimage: "rally3.jpg",
    },
    {
        SimID: 4,
        SimListName: "Endurance Racing Pro",
        PricePerHour: 1800,
        ListDescription:
            "Built for long-distance racing with ergonomic seat, climate control, and professional-grade equipment. Host your team's practice sessions here.",
        HostID: 3,
        ModID: 4,
        ModelName: "Endurance Pro",
        Description: "Endurance racing with climate control",
        BrandID: 2,
        BrandName: "GT Racing",
        FName: "Mike",
        LName: "Williams",
        AddressDetail: "321 Circuit Lane, East Zone",
        Lat: 13.7542,
        Long: 100.561,
        Htel: "02-456-7890",
        firstimage: "endurance1.jpg",
        secondimage: "endurance2.jpg",
        thirdimage: "endurance3.jpg",
    },
    {
        SimID: 5,
        SimListName: "F1 Virtual Cockpit",
        PricePerHour: 2000,
        ListDescription:
            "Step into an authentic F1 cockpit replica with real F1 steering wheel, advanced telemetry, and professional coaching available.",
        HostID: 4,
        ModID: 5,
        ModelName: "F1 Cockpit",
        Description: "Authentic F1 cockpit with telemetry",
        BrandID: 3,
        BrandName: "F1 Simulators",
        FName: "Emma",
        LName: "Davis",
        AddressDetail: "555 Grand Prix Street, West End",
        Lat: 13.7275,
        Long: 100.524,
        Htel: "02-567-8901",
        firstimage: "f1cockpit1.jpg",
        secondimage: "f1cockpit2.jpg",
        thirdimage: "f1cockpit3.jpg",
    },
    {
        SimID: 6,
        SimListName: "GT3 Racing Experience",
        PricePerHour: 1600,
        ListDescription:
            "Premium GT3 simulator with carbon fiber chassis, direct drive motor, and ultra-wide curved display for maximum visibility.",
        HostID: 2,
        ModID: 6,
        ModelName: "GT3 Elite",
        Description: "GT3 simulator with carbon fiber chassis",
        BrandID: 2,
        BrandName: "GT Racing",
        FName: "Sarah",
        LName: "Johnson",
        AddressDetail: "888 Motorsport Plaza, City Center",
        Lat: 13.7412,
        Long: 100.5145,
        Htel: "02-678-9012",
        firstimage: "gt3_1.jpg",
        secondimage: "gt3_2.jpg",
        thirdimage: "gt3_3.jpg",
    },
    {
        SimID: 7,
        SimListName: "Street Racing Simulator",
        PricePerHour: 900,
        ListDescription:
            "Urban racing experience with manual gearbox, adjustable seat position, and real-time traffic simulation for authentic street racing.",
        HostID: 5,
        ModID: 7,
        ModelName: "Street Pro",
        Description: "Street racing with manual gearbox",
        BrandID: 4,
        BrandName: "Urban Racing",
        FName: "Chris",
        LName: "Brown",
        AddressDetail: "777 Urban Drive, Downtown",
        Lat: 13.7588,
        Long: 100.5312,
        Htel: "02-789-0123",
        firstimage: "street1.jpg",
        secondimage: "street2.jpg",
        thirdimage: "street3.jpg",
    },
    {
        SimID: 8,
        SimListName: "Pro Drift Simulator",
        PricePerHour: 1100,
        ListDescription:
            "Master the art of drifting with our specialized simulator featuring hydraulic handbrake, drift seat, and angle kit steering.",
        HostID: 6,
        ModID: 8,
        ModelName: "Drift Master",
        Description: "Drift simulator with hydraulic handbrake",
        BrandID: 4,
        BrandName: "Urban Racing",
        FName: "Lisa",
        LName: "Taylor",
        AddressDetail: "999 Slide Street, East District",
        Lat: 13.749,
        Long: 100.5555,
        Htel: "02-890-1234",
        firstimage: "drift1.jpg",
        secondimage: "drift2.jpg",
        thirdimage: "drift3.jpg",
    },
    {
        SimID: 9,
        SimListName: "Le Mans Prototype Sim",
        PricePerHour: 1700,
        ListDescription:
            "Experience prototype racing with this LMP-style cockpit. Features include night racing mode, weather simulation, and team radio.",
        HostID: 3,
        ModID: 9,
        ModelName: "LMP Pro",
        Description: "Prototype simulator with weather effects",
        BrandID: 3,
        BrandName: "F1 Simulators",
        FName: "Mike",
        LName: "Williams",
        AddressDetail: "111 Endurance Way, South Side",
        Lat: 13.732,
        Long: 100.5465,
        Htel: "02-901-2345",
        firstimage: "lmp1.jpg",
        secondimage: "lmp2.jpg",
        thirdimage: "lmp3.jpg",
    },
    {
        SimID: 10,
        SimListName: "NASCAR Thunder Sim",
        PricePerHour: 1300,
        ListDescription:
            "Feel the power of oval racing with our NASCAR simulator. Heavy-duty wheel, authentic stock car seat, and multi-screen setup.",
        HostID: 7,
        ModID: 10,
        ModelName: "NASCAR Pro",
        Description: "NASCAR simulator with multi-screen",
        BrandID: 5,
        BrandName: "Thunder Racing",
        FName: "David",
        LName: "Anderson",
        AddressDetail: "222 Speedway Drive, West Zone",
        Lat: 13.739,
        Long: 100.498,
        Htel: "02-012-3456",
        firstimage: "nascar1.jpg",
        secondimage: "nascar2.jpg",
        thirdimage: "nascar3.jpg",
    },
];

export const mockBookings: Booking[] = [
    {
        BookingID: 1,
        SimID: 1,
        CustomerID: 1,
        BookingDate: "2026-03-15",
        StatusID: 1,
        Statusname: "Confirmed",
        TotalPrice: 3000,
        firstimage: "formula1.jpg",
    },
    {
        BookingID: 2,
        SimID: 3,
        CustomerID: 1,
        BookingDate: "2026-03-20",
        StatusID: 1,
        Statusname: "Confirmed",
        TotalPrice: 2000,
        firstimage: "rally1.jpg",
    },
    {
        BookingID: 3,
        SimID: 5,
        CustomerID: 1,
        BookingDate: "2026-02-10",
        StatusID: 3,
        Statusname: "Completed",
        TotalPrice: 4000,
        firstimage: "f1cockpit1.jpg",
    },
    {
        BookingID: 4,
        SimID: 2,
        CustomerID: 1,
        BookingDate: "2026-04-05",
        StatusID: 2,
        Statusname: "Pending",
        TotalPrice: 2400,
        firstimage: "gt1.jpg",
    },
];

export const mockSchedules = [
    {
        SimID: 1,
        date: "2026-03-01",
        availableSlots: [
            { startTime: "09:00", endTime: "11:00" },
            { startTime: "11:00", endTime: "13:00" },
            { startTime: "18:00", endTime: "20:00" },
            { startTime: "20:00", endTime: "22:00" },
        ],
    },
    {
        SimID: 1,
        date: "2026-03-02",
        availableSlots: [
            { startTime: "09:00", endTime: "11:00" },
            { startTime: "13:00", endTime: "15:00" },
            { startTime: "15:00", endTime: "17:00" },
        ],
    },
];

// Helper to generate more products dynamically
export function generateMockProducts(count: number): Product[] {
    const products: Product[] = [...mockProducts];
    const names = [
        "Ultimate Racing Rig",
        "Speed Demon Simulator",
        "Track Master Pro",
        "Circuit Champion",
        "Racing Elite Setup",
    ];
    const modelNames = ["Pro", "Elite", "Master", "Champion", "Ultimate"];
    const brandNames = [
        "SimRacing Pro",
        "GT Racing",
        "F1 Simulators",
        "Urban Racing",
        "Thunder Racing",
    ];

    for (let i = mockProducts.length; i < count; i++) {
        products.push({
            SimID: i + 1,
            SimListName: `${names[i % names.length]} ${i + 1}`,
            PricePerHour: 800 + (i % 15) * 100,
            ListDescription: `Professional racing simulator with advanced features. Simulator ID: ${i + 1}`,
            HostID: (i % 7) + 1,
            ModID: i + 1,
            ModelName: `${modelNames[i % modelNames.length]} ${i + 1}`,
            Description: `High-quality simulator with professional equipment`,
            BrandID: (i % 5) + 1,
            BrandName: brandNames[i % brandNames.length],
            FName: ["John", "Sarah", "Mike", "Emma", "Chris", "Lisa", "David"][
                i % 7
            ],
            LName: [
                "Smith",
                "Johnson",
                "Williams",
                "Davis",
                "Brown",
                "Taylor",
                "Anderson",
            ][i % 7],
            AddressDetail: `${100 + i} Racing Street, District ${(i % 5) + 1}`,
            Lat: 13.72 + Math.random() * 0.08,
            Long: 100.49 + Math.random() * 0.1,
            Htel: `02-${String(Math.floor(Math.random() * 900 + 100))}-${String(Math.floor(Math.random() * 9000 + 1000))}`,
            firstimage: `sim${i + 1}_1.jpg`,
            secondimage: `sim${i + 1}_2.jpg`,
            thirdimage: `sim${i + 1}_3.jpg`,
        });
    }

    return products;
}
